version: '3'

services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PORT=5001
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped 